services:
  dixel-app:
    build: .
    container_name: dixel-mini-app
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dixel-app.rule=Host(`opt-zakaz.dixel.store`)"
      - "traefik.http.routers.dixel-app.entrypoints=https"
      - "traefik.http.routers.dixel-app.tls=true"
      - "traefik.http.routers.dixel-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.dixel-app.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    networks:
      - web
      - proxy

  dixel-importer:
    build: .
    container_name: dixel-importer
    restart: unless-stopped
    env_file:
      - .env
    command: ["node", "scripts/import-schedule.js"]
    networks:
      - web

  dixel-bot:
    build: .
    container_name: dixel-bot
    restart: unless-stopped
    env_file:
      - .env
    command: ["node", "server/bot/index.js"]
    networks:
      - web

networks:
  web:
    driver: bridge
  proxy:
    external: true
